# Generated by Django 4.2.7 on 2023-11-14 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='musician',
            old_name='name_band_or_solo',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='musician',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
    ]
